// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type CreateKafkaupstreamPluginRequest struct {
	// The name or UUID of the workspace
	Workspace           string                     `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	KafkaUpstreamPlugin shared.KafkaUpstreamPlugin `request:"mediaType=application/json"`
}

func (c CreateKafkaupstreamPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKafkaupstreamPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"workspace", "KafkaUpstreamPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateKafkaupstreamPluginRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateKafkaupstreamPluginRequest) GetKafkaUpstreamPlugin() shared.KafkaUpstreamPlugin {
	if c == nil {
		return shared.KafkaUpstreamPlugin{}
	}
	return c.KafkaUpstreamPlugin
}

type CreateKafkaupstreamPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created KafkaUpstream plugin
	KafkaUpstreamPlugin *shared.KafkaUpstreamPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c *CreateKafkaupstreamPluginResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateKafkaupstreamPluginResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateKafkaupstreamPluginResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateKafkaupstreamPluginResponse) GetKafkaUpstreamPlugin() *shared.KafkaUpstreamPlugin {
	if c == nil {
		return nil
	}
	return c.KafkaUpstreamPlugin
}

func (c *CreateKafkaupstreamPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
