// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type CreateLdapauthPluginRequest struct {
	// The name or UUID of the workspace
	Workspace      string                `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	LdapAuthPlugin shared.LdapAuthPlugin `request:"mediaType=application/json"`
}

func (c CreateLdapauthPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateLdapauthPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"workspace", "LdapAuthPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateLdapauthPluginRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateLdapauthPluginRequest) GetLdapAuthPlugin() shared.LdapAuthPlugin {
	if c == nil {
		return shared.LdapAuthPlugin{}
	}
	return c.LdapAuthPlugin
}

type CreateLdapauthPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created LdapAuth plugin
	LdapAuthPlugin *shared.LdapAuthPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c *CreateLdapauthPluginResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateLdapauthPluginResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateLdapauthPluginResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateLdapauthPluginResponse) GetLdapAuthPlugin() *shared.LdapAuthPlugin {
	if c == nil {
		return nil
	}
	return c.LdapAuthPlugin
}

func (c *CreateLdapauthPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
