// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type CreateRequestvalidatorPluginRequest struct {
	// The name or UUID of the workspace
	Workspace              string                        `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	RequestValidatorPlugin shared.RequestValidatorPlugin `request:"mediaType=application/json"`
}

func (c CreateRequestvalidatorPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRequestvalidatorPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"workspace", "RequestValidatorPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateRequestvalidatorPluginRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateRequestvalidatorPluginRequest) GetRequestValidatorPlugin() shared.RequestValidatorPlugin {
	if c == nil {
		return shared.RequestValidatorPlugin{}
	}
	return c.RequestValidatorPlugin
}

type CreateRequestvalidatorPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created RequestValidator plugin
	RequestValidatorPlugin *shared.RequestValidatorPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c *CreateRequestvalidatorPluginResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateRequestvalidatorPluginResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateRequestvalidatorPluginResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateRequestvalidatorPluginResponse) GetRequestValidatorPlugin() *shared.RequestValidatorPlugin {
	if c == nil {
		return nil
	}
	return c.RequestValidatorPlugin
}

func (c *CreateRequestvalidatorPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
