// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type CreateTlshandshakemodifierPluginRequest struct {
	// The name or UUID of the workspace
	Workspace                  string                            `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	TLSHandshakeModifierPlugin shared.TLSHandshakeModifierPlugin `request:"mediaType=application/json"`
}

func (c CreateTlshandshakemodifierPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTlshandshakemodifierPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"workspace", "TlsHandshakeModifierPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateTlshandshakemodifierPluginRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateTlshandshakemodifierPluginRequest) GetTLSHandshakeModifierPlugin() shared.TLSHandshakeModifierPlugin {
	if c == nil {
		return shared.TLSHandshakeModifierPlugin{}
	}
	return c.TLSHandshakeModifierPlugin
}

type CreateTlshandshakemodifierPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created TlsHandshakeModifier plugin
	TLSHandshakeModifierPlugin *shared.TLSHandshakeModifierPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c *CreateTlshandshakemodifierPluginResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateTlshandshakemodifierPluginResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateTlshandshakemodifierPluginResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateTlshandshakemodifierPluginResponse) GetTLSHandshakeModifierPlugin() *shared.TLSHandshakeModifierPlugin {
	if c == nil {
		return nil
	}
	return c.TLSHandshakeModifierPlugin
}

func (c *CreateTlshandshakemodifierPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
