// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type CreateGraphqlratelimitingadvancedPluginRequest struct {
	// The name or UUID of the workspace
	Workspace                         string                                   `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	GraphqlRateLimitingAdvancedPlugin shared.GraphqlRateLimitingAdvancedPlugin `request:"mediaType=application/json"`
}

func (c CreateGraphqlratelimitingadvancedPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateGraphqlratelimitingadvancedPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"workspace", "GraphqlRateLimitingAdvancedPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateGraphqlratelimitingadvancedPluginRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateGraphqlratelimitingadvancedPluginRequest) GetGraphqlRateLimitingAdvancedPlugin() shared.GraphqlRateLimitingAdvancedPlugin {
	if c == nil {
		return shared.GraphqlRateLimitingAdvancedPlugin{}
	}
	return c.GraphqlRateLimitingAdvancedPlugin
}

type CreateGraphqlratelimitingadvancedPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created GraphqlRateLimitingAdvanced plugin
	GraphqlRateLimitingAdvancedPlugin *shared.GraphqlRateLimitingAdvancedPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c *CreateGraphqlratelimitingadvancedPluginResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateGraphqlratelimitingadvancedPluginResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateGraphqlratelimitingadvancedPluginResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateGraphqlratelimitingadvancedPluginResponse) GetGraphqlRateLimitingAdvancedPlugin() *shared.GraphqlRateLimitingAdvancedPlugin {
	if c == nil {
		return nil
	}
	return c.GraphqlRateLimitingAdvancedPlugin
}

func (c *CreateGraphqlratelimitingadvancedPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
