// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type DeleteGroupsGroupIDOrNameRolesRequest struct {
	// ID of the Group to lookup
	GroupID string `pathParam:"style=simple,explode=false,name=GroupId"`
	// ID of the role to remove from the group.
	RbacRoleID  string `queryParam:"style=form,explode=true,name=rbac_role_id"`
	WorkspaceID string `queryParam:"style=form,explode=true,name=workspace_id"`
}

func (d DeleteGroupsGroupIDOrNameRolesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteGroupsGroupIDOrNameRolesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"GroupId", "rbac_role_id", "workspace_id"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteGroupsGroupIDOrNameRolesRequest) GetGroupID() string {
	if d == nil {
		return ""
	}
	return d.GroupID
}

func (d *DeleteGroupsGroupIDOrNameRolesRequest) GetRbacRoleID() string {
	if d == nil {
		return ""
	}
	return d.RbacRoleID
}

func (d *DeleteGroupsGroupIDOrNameRolesRequest) GetWorkspaceID() string {
	if d == nil {
		return ""
	}
	return d.WorkspaceID
}

type DeleteGroupsGroupIDOrNameRolesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (d DeleteGroupsGroupIDOrNameRolesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteGroupsGroupIDOrNameRolesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteGroupsGroupIDOrNameRolesResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteGroupsGroupIDOrNameRolesResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteGroupsGroupIDOrNameRolesResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteGroupsGroupIDOrNameRolesResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if d == nil {
		return nil
	}
	return d.GatewayUnauthorizedError
}
