// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type DeleteSniRequest struct {
	// ID or name of the SNI to lookup
	SNIIDOrName string `pathParam:"style=simple,explode=false,name=SNIIdOrName"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
}

func (d DeleteSniRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteSniRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"SNIIdOrName", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteSniRequest) GetSNIIDOrName() string {
	if d == nil {
		return ""
	}
	return d.SNIIDOrName
}

func (d *DeleteSniRequest) GetWorkspace() string {
	if d == nil {
		return ""
	}
	return d.Workspace
}

type DeleteSniResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (d *DeleteSniResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteSniResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteSniResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteSniResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if d == nil {
		return nil
	}
	return d.GatewayUnauthorizedError
}
