// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type DeleteAillmasjudgePluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
}

func (d DeleteAillmasjudgePluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAillmasjudgePluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"PluginId", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAillmasjudgePluginRequest) GetPluginID() string {
	if d == nil {
		return ""
	}
	return d.PluginID
}

func (d *DeleteAillmasjudgePluginRequest) GetWorkspace() string {
	if d == nil {
		return ""
	}
	return d.Workspace
}

type DeleteAillmasjudgePluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (d *DeleteAillmasjudgePluginResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAillmasjudgePluginResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAillmasjudgePluginResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteAillmasjudgePluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if d == nil {
		return nil
	}
	return d.GatewayUnauthorizedError
}
