// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type GetCustomPluginRequest struct {
	// ID or name of the CustomPlugin to lookup
	CustomPluginIDOrName string `pathParam:"style=simple,explode=false,name=CustomPluginIdOrName"`
}

func (g GetCustomPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"CustomPluginIdOrName"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomPluginRequest) GetCustomPluginIDOrName() string {
	if g == nil {
		return ""
	}
	return g.CustomPluginIDOrName
}

type GetCustomPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched CustomPlugin
	CustomPlugin *shared.CustomPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (g GetCustomPluginResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomPluginResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomPluginResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetCustomPluginResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCustomPluginResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetCustomPluginResponse) GetCustomPlugin() *shared.CustomPlugin {
	if g == nil {
		return nil
	}
	return g.CustomPlugin
}

func (g *GetCustomPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if g == nil {
		return nil
	}
	return g.GatewayUnauthorizedError
}
