// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type GetCaCertificateRequest struct {
	// ID of the CA Certificate to lookup
	CACertificateID string `pathParam:"style=simple,explode=false,name=CACertificateId"`
}

func (g *GetCaCertificateRequest) GetCACertificateID() string {
	if g == nil {
		return ""
	}
	return g.CACertificateID
}

type GetCaCertificateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched CA Certificate
	CACertificate *shared.CACertificate
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (g *GetCaCertificateResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetCaCertificateResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCaCertificateResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetCaCertificateResponse) GetCACertificate() *shared.CACertificate {
	if g == nil {
		return nil
	}
	return g.CACertificate
}

func (g *GetCaCertificateResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if g == nil {
		return nil
	}
	return g.GatewayUnauthorizedError
}
