// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type GetRbacRoleEntitieRequest struct {
	// ID of the RBAC Role Entity to lookup
	RBACRoleEntityID string `pathParam:"style=simple,explode=false,name=RBACRoleEntityId"`
	// ID of the RBAC Role to lookup
	RBACRoleIDForNestedEntities string `pathParam:"style=simple,explode=false,name=RBACRoleIdForNestedEntities"`
	// The name of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
}

func (g GetRbacRoleEntitieRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRbacRoleEntitieRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"RBACRoleEntityId", "RBACRoleIdForNestedEntities", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRbacRoleEntitieRequest) GetRBACRoleEntityID() string {
	if g == nil {
		return ""
	}
	return g.RBACRoleEntityID
}

func (g *GetRbacRoleEntitieRequest) GetRBACRoleIDForNestedEntities() string {
	if g == nil {
		return ""
	}
	return g.RBACRoleIDForNestedEntities
}

func (g *GetRbacRoleEntitieRequest) GetWorkspace() string {
	if g == nil {
		return ""
	}
	return g.Workspace
}

type GetRbacRoleEntitieResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully fetched RBAC Role Entity
	RBACRoleEntity *shared.RBACRoleEntity
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (g GetRbacRoleEntitieResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRbacRoleEntitieResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (g *GetRbacRoleEntitieResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRbacRoleEntitieResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRbacRoleEntitieResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRbacRoleEntitieResponse) GetRBACRoleEntity() *shared.RBACRoleEntity {
	if g == nil {
		return nil
	}
	return g.RBACRoleEntity
}

func (g *GetRbacRoleEntitieResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if g == nil {
		return nil
	}
	return g.GatewayUnauthorizedError
}
