// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListGroupRolesRequest struct {
	Groups string `pathParam:"style=simple,explode=false,name=groups"`
}

func (o *ListGroupRolesRequest) GetGroups() string {
	if o == nil {
		return ""
	}
	return o.Groups
}

type Group struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (o *Group) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Group) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type RbacRole struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (o *RbacRole) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RbacRole) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type Workspace struct {
	ID *string `json:"id,omitempty"`
}

func (o *Workspace) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

type ListGroupRolesResponseBody struct {
	Group     *Group     `json:"group,omitempty"`
	RbacRole  *RbacRole  `json:"rbac_role,omitempty"`
	Workspace *Workspace `json:"workspace,omitempty"`
}

func (o *ListGroupRolesResponseBody) GetGroup() *Group {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *ListGroupRolesResponseBody) GetRbacRole() *RbacRole {
	if o == nil {
		return nil
	}
	return o.RbacRole
}

func (o *ListGroupRolesResponseBody) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}
	return o.Workspace
}

type ListGroupRolesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved the roles
	ResponseBodies []ListGroupRolesResponseBody
}

func (o *ListGroupRolesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListGroupRolesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListGroupRolesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListGroupRolesResponse) GetResponseBodies() []ListGroupRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
