// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type ListPluginRequest struct {
	// Number of resources to be returned.
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
}

func (l ListPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"workspace"}); err != nil {
		return err
	}
	return nil
}

func (l *ListPluginRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListPluginRequest) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListPluginRequest) GetTags() *string {
	if l == nil {
		return nil
	}
	return l.Tags
}

func (l *ListPluginRequest) GetWorkspace() string {
	if l == nil {
		return ""
	}
	return l.Workspace
}

// ListPluginResponseBody - A successful response listing Plugins
type ListPluginResponseBody struct {
	Data []shared.Plugin `json:"data,omitempty"`
	// URI to the next page (may be null)
	Next *string `json:"next,omitempty"`
	// Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
	Offset *string `json:"offset,omitempty"`
}

func (l *ListPluginResponseBody) GetData() []shared.Plugin {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListPluginResponseBody) GetNext() *string {
	if l == nil {
		return nil
	}
	return l.Next
}

func (l *ListPluginResponseBody) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A successful response listing Plugins
	Object *ListPluginResponseBody
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (l *ListPluginResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPluginResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPluginResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPluginResponse) GetObject() *ListPluginResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if l == nil {
		return nil
	}
	return l.GatewayUnauthorizedError
}
