// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpdateRatelimitingPluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The name or UUID of the workspace
	Workspace          string                    `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	RateLimitingPlugin shared.RateLimitingPlugin `request:"mediaType=application/json"`
}

func (u UpdateRatelimitingPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateRatelimitingPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"PluginId", "workspace", "RateLimitingPlugin"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateRatelimitingPluginRequest) GetPluginID() string {
	if u == nil {
		return ""
	}
	return u.PluginID
}

func (u *UpdateRatelimitingPluginRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpdateRatelimitingPluginRequest) GetRateLimitingPlugin() shared.RateLimitingPlugin {
	if u == nil {
		return shared.RateLimitingPlugin{}
	}
	return u.RateLimitingPlugin
}

type UpdateRatelimitingPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// RateLimiting plugin
	RateLimitingPlugin *shared.RateLimitingPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpdateRatelimitingPluginResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateRatelimitingPluginResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateRatelimitingPluginResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateRatelimitingPluginResponse) GetRateLimitingPlugin() *shared.RateLimitingPlugin {
	if u == nil {
		return nil
	}
	return u.RateLimitingPlugin
}

func (u *UpdateRatelimitingPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
