// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpdateCaCertificateRequest struct {
	// ID of the CA Certificate to lookup
	CACertificateID string `pathParam:"style=simple,explode=false,name=CACertificateId"`
	// Fields of the CA Certificate that need to be updated
	CACertificate shared.CACertificateInput `request:"mediaType=application/json"`
}

func (o *UpdateCaCertificateRequest) GetCACertificateID() string {
	if o == nil {
		return ""
	}
	return o.CACertificateID
}

func (o *UpdateCaCertificateRequest) GetCACertificate() shared.CACertificateInput {
	if o == nil {
		return shared.CACertificateInput{}
	}
	return o.CACertificate
}

type UpdateCaCertificateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully updated CA Certificate
	CACertificate *shared.CACertificate
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (o *UpdateCaCertificateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateCaCertificateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateCaCertificateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateCaCertificateResponse) GetCACertificate() *shared.CACertificate {
	if o == nil {
		return nil
	}
	return o.CACertificate
}

func (o *UpdateCaCertificateResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if o == nil {
		return nil
	}
	return o.GatewayUnauthorizedError
}
