// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpdateAiratelimitingadvancedPluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The name or UUID of the workspace
	Workspace                    string                              `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	AiRateLimitingAdvancedPlugin shared.AiRateLimitingAdvancedPlugin `request:"mediaType=application/json"`
}

func (u UpdateAiratelimitingadvancedPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAiratelimitingadvancedPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"PluginId", "workspace", "AiRateLimitingAdvancedPlugin"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAiratelimitingadvancedPluginRequest) GetPluginID() string {
	if u == nil {
		return ""
	}
	return u.PluginID
}

func (u *UpdateAiratelimitingadvancedPluginRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpdateAiratelimitingadvancedPluginRequest) GetAiRateLimitingAdvancedPlugin() shared.AiRateLimitingAdvancedPlugin {
	if u == nil {
		return shared.AiRateLimitingAdvancedPlugin{}
	}
	return u.AiRateLimitingAdvancedPlugin
}

type UpdateAiratelimitingadvancedPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// AiRateLimitingAdvanced plugin
	AiRateLimitingAdvancedPlugin *shared.AiRateLimitingAdvancedPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpdateAiratelimitingadvancedPluginResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAiratelimitingadvancedPluginResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAiratelimitingadvancedPluginResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAiratelimitingadvancedPluginResponse) GetAiRateLimitingAdvancedPlugin() *shared.AiRateLimitingAdvancedPlugin {
	if u == nil {
		return nil
	}
	return u.AiRateLimitingAdvancedPlugin
}

func (u *UpdateAiratelimitingadvancedPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
