// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpdateSolaceupstreamPluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The name or UUID of the workspace
	Workspace            string                      `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	SolaceUpstreamPlugin shared.SolaceUpstreamPlugin `request:"mediaType=application/json"`
}

func (u UpdateSolaceupstreamPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSolaceupstreamPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"PluginId", "workspace", "SolaceUpstreamPlugin"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSolaceupstreamPluginRequest) GetPluginID() string {
	if u == nil {
		return ""
	}
	return u.PluginID
}

func (u *UpdateSolaceupstreamPluginRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpdateSolaceupstreamPluginRequest) GetSolaceUpstreamPlugin() shared.SolaceUpstreamPlugin {
	if u == nil {
		return shared.SolaceUpstreamPlugin{}
	}
	return u.SolaceUpstreamPlugin
}

type UpdateSolaceupstreamPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// SolaceUpstream plugin
	SolaceUpstreamPlugin *shared.SolaceUpstreamPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpdateSolaceupstreamPluginResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateSolaceupstreamPluginResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSolaceupstreamPluginResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateSolaceupstreamPluginResponse) GetSolaceUpstreamPlugin() *shared.SolaceUpstreamPlugin {
	if u == nil {
		return nil
	}
	return u.SolaceUpstreamPlugin
}

func (u *UpdateSolaceupstreamPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
