// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpdateOpentelemetryPluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The name or UUID of the workspace
	Workspace           string                     `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	OpentelemetryPlugin shared.OpentelemetryPlugin `request:"mediaType=application/json"`
}

func (u UpdateOpentelemetryPluginRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOpentelemetryPluginRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"PluginId", "workspace", "OpentelemetryPlugin"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOpentelemetryPluginRequest) GetPluginID() string {
	if u == nil {
		return ""
	}
	return u.PluginID
}

func (u *UpdateOpentelemetryPluginRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpdateOpentelemetryPluginRequest) GetOpentelemetryPlugin() shared.OpentelemetryPlugin {
	if u == nil {
		return shared.OpentelemetryPlugin{}
	}
	return u.OpentelemetryPlugin
}

type UpdateOpentelemetryPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Opentelemetry plugin
	OpentelemetryPlugin *shared.OpentelemetryPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpdateOpentelemetryPluginResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateOpentelemetryPluginResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateOpentelemetryPluginResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateOpentelemetryPluginResponse) GetOpentelemetryPlugin() *shared.OpentelemetryPlugin {
	if u == nil {
		return nil
	}
	return u.OpentelemetryPlugin
}

func (u *UpdateOpentelemetryPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
