// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpsertJwtWithConsumerRequest struct {
	// Consumer ID for nested entities
	ConsumerID string `pathParam:"style=simple,explode=false,name=ConsumerIdForNestedEntities"`
	// ID of the JWT to lookup
	JWTID string `pathParam:"style=simple,explode=false,name=JWTId"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	// Description of the JWT
	JWTWithoutParents *shared.JWTWithoutParents `request:"mediaType=application/json"`
}

func (u UpsertJwtWithConsumerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertJwtWithConsumerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ConsumerIdForNestedEntities", "JWTId", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (u *UpsertJwtWithConsumerRequest) GetConsumerID() string {
	if u == nil {
		return ""
	}
	return u.ConsumerID
}

func (u *UpsertJwtWithConsumerRequest) GetJWTID() string {
	if u == nil {
		return ""
	}
	return u.JWTID
}

func (u *UpsertJwtWithConsumerRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpsertJwtWithConsumerRequest) GetJWTWithoutParents() *shared.JWTWithoutParents {
	if u == nil {
		return nil
	}
	return u.JWTWithoutParents
}

type UpsertJwtWithConsumerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully upserted JWT
	Jwt *shared.Jwt
}

func (u *UpsertJwtWithConsumerResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertJwtWithConsumerResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertJwtWithConsumerResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertJwtWithConsumerResponse) GetJwt() *shared.Jwt {
	if u == nil {
		return nil
	}
	return u.Jwt
}
