// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpsertRouteRouteExpressionRequest struct {
	// ID or name of the Route to lookup
	RouteIDOrName string `pathParam:"style=simple,explode=false,name=RouteIdOrName"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	// Description of the Route
	RouteExpression shared.RouteExpression `request:"mediaType=application/json"`
}

func (u UpsertRouteRouteExpressionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertRouteRouteExpressionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"RouteIdOrName", "workspace", "RouteExpression"}); err != nil {
		return err
	}
	return nil
}

func (u *UpsertRouteRouteExpressionRequest) GetRouteIDOrName() string {
	if u == nil {
		return ""
	}
	return u.RouteIDOrName
}

func (u *UpsertRouteRouteExpressionRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpsertRouteRouteExpressionRequest) GetRouteExpression() shared.RouteExpression {
	if u == nil {
		return shared.RouteExpression{}
	}
	return u.RouteExpression
}

type UpsertRouteRouteExpressionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully upserted Route
	RouteExpression *shared.RouteExpression
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpsertRouteRouteExpressionResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertRouteRouteExpressionResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertRouteRouteExpressionResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertRouteRouteExpressionResponse) GetRouteExpression() *shared.RouteExpression {
	if u == nil {
		return nil
	}
	return u.RouteExpression
}

func (u *UpsertRouteRouteExpressionResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
