// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpsertServiceRequest struct {
	// ID or name of the Service to lookup
	ServiceIDOrName string `pathParam:"style=simple,explode=false,name=ServiceIdOrName"`
	// Description of the Service
	Service shared.ServiceInput `request:"mediaType=application/json"`
}

func (o *UpsertServiceRequest) GetServiceIDOrName() string {
	if o == nil {
		return ""
	}
	return o.ServiceIDOrName
}

func (o *UpsertServiceRequest) GetService() shared.ServiceInput {
	if o == nil {
		return shared.ServiceInput{}
	}
	return o.Service
}

type UpsertServiceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully upserted Service
	Service *shared.Service
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (o *UpsertServiceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpsertServiceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpsertServiceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpsertServiceResponse) GetService() *shared.Service {
	if o == nil {
		return nil
	}
	return o.Service
}

func (o *UpsertServiceResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if o == nil {
		return nil
	}
	return o.GatewayUnauthorizedError
}
