// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpsertKeySetRequest struct {
	// ID or name of the KeySet to lookup
	KeySetIDOrName string `pathParam:"style=simple,explode=false,name=KeySetIdOrName"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	// Description of the KeySet
	KeySet *shared.KeySet `request:"mediaType=application/json"`
}

func (u UpsertKeySetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertKeySetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"KeySetIdOrName", "workspace"}); err != nil {
		return err
	}
	return nil
}

func (u *UpsertKeySetRequest) GetKeySetIDOrName() string {
	if u == nil {
		return ""
	}
	return u.KeySetIDOrName
}

func (u *UpsertKeySetRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpsertKeySetRequest) GetKeySet() *shared.KeySet {
	if u == nil {
		return nil
	}
	return u.KeySet
}

type UpsertKeySetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully upserted KeySet
	KeySet *shared.KeySet
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpsertKeySetResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertKeySetResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertKeySetResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertKeySetResponse) GetKeySet() *shared.KeySet {
	if u == nil {
		return nil
	}
	return u.KeySet
}

func (u *UpsertKeySetResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
