// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
	"net/http"
)

type UpsertVaultRequest struct {
	// ID or prefix of the Vault to lookup
	VaultIDOrPrefix string `pathParam:"style=simple,explode=false,name=VaultIdOrPrefix"`
	// The name or UUID of the workspace
	Workspace string `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	// Description of the Vault
	Vault shared.Vault `request:"mediaType=application/json"`
}

func (u UpsertVaultRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertVaultRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"VaultIdOrPrefix", "workspace", "Vault"}); err != nil {
		return err
	}
	return nil
}

func (u *UpsertVaultRequest) GetVaultIDOrPrefix() string {
	if u == nil {
		return ""
	}
	return u.VaultIDOrPrefix
}

func (u *UpsertVaultRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpsertVaultRequest) GetVault() shared.Vault {
	if u == nil {
		return shared.Vault{}
	}
	return u.Vault
}

type UpsertVaultResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully upserted Vault
	Vault *shared.Vault
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u *UpsertVaultResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertVaultResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertVaultResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertVaultResponse) GetVault() *shared.Vault {
	if u == nil {
		return nil
	}
	return u.Vault
}

func (u *UpsertVaultResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
