// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/internal/utils"
)

type RBACRole struct {
	// Additional comment or description for the RBAC role.
	Comment *string `json:"comment,omitempty"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// Indicates whether the RBAC role is the default role.
	IsDefault *bool `json:"is_default,omitempty"`
	// The name of the RBAC role.
	Name *string `json:"name"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

func (r RBACRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RBACRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RBACRole) GetComment() *string {
	if r == nil {
		return nil
	}
	return r.Comment
}

func (r *RBACRole) GetCreatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RBACRole) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RBACRole) GetIsDefault() *bool {
	if r == nil {
		return nil
	}
	return r.IsDefault
}

func (r *RBACRole) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RBACRole) GetUpdatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}
