// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ClientCertificate - Certificate to be used as client certificate while TLS handshaking to the upstream server.
type ClientCertificate struct {
	ID *string `json:"id,omitempty"`
}

func (c *ClientCertificate) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

// Protocol - The protocol used to communicate with the upstream.
type Protocol string

const (
	ProtocolGrpc           Protocol = "grpc"
	ProtocolGrpcs          Protocol = "grpcs"
	ProtocolHTTP           Protocol = "http"
	ProtocolHTTPS          Protocol = "https"
	ProtocolTCP            Protocol = "tcp"
	ProtocolTLS            Protocol = "tls"
	ProtocolTLSPassthrough Protocol = "tls_passthrough"
	ProtocolUDP            Protocol = "udp"
	ProtocolWs             Protocol = "ws"
	ProtocolWss            Protocol = "wss"
)

func (e Protocol) ToPointer() *Protocol {
	return &e
}
func (e *Protocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "http":
		fallthrough
	case "https":
		fallthrough
	case "tcp":
		fallthrough
	case "tls":
		fallthrough
	case "tls_passthrough":
		fallthrough
	case "udp":
		fallthrough
	case "ws":
		fallthrough
	case "wss":
		*e = Protocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Protocol: %v", v)
	}
}

// TLSSans - Additional Subject Alternative Names that can be matched on Upstream server's TLS certificate (in addition to `host`).
type TLSSans struct {
	// A dnsName for TLS verification.
	Dnsnames []string `json:"dnsnames,omitempty"`
	// An URI for TLS verification.
	Uris []string `json:"uris,omitempty"`
}

func (t *TLSSans) GetDnsnames() []string {
	if t == nil {
		return nil
	}
	return t.Dnsnames
}

func (t *TLSSans) GetUris() []string {
	if t == nil {
		return nil
	}
	return t.Uris
}

// ServiceOutput - Service entities, as the name implies, are abstractions of each of your own upstream services. Examples of Services would be a data transformation microservice, a billing API, etc. The main attribute of a Service is its URL (where Kong should proxy traffic to), which can be set as a single string or by specifying its `protocol`, `host`, `port` and `path` individually. Services are associated to Routes (a Service can have many Routes associated with it). Routes are entry-points in Kong and define rules to match client requests. Once a Route is matched, Kong proxies the request to its associated Service. See the [Proxy Reference][proxy-reference] for a detailed explanation of how Kong proxies traffic.
type ServiceOutput struct {
	// Array of `CA Certificate` object UUIDs that are used to build the trust store while verifying upstream server's TLS certificate. If set to `null` when Nginx default is respected. If default CA list in Nginx are not specified and TLS verification is enabled, then handshake with upstream server will always fail (because no CA are trusted).
	CaCertificates []string `json:"ca_certificates,omitempty"`
	// Certificate to be used as client certificate while TLS handshaking to the upstream server.
	ClientCertificate *ClientCertificate `json:"client_certificate,omitempty"`
	// The timeout in milliseconds for establishing a connection to the upstream server.
	ConnectTimeout *int64 `json:"connect_timeout,omitempty"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the Service is active. If set to `false`, the proxy behavior will be as if any routes attached to it do not exist (404). Default: `true`.
	Enabled *bool `json:"enabled,omitempty"`
	// The host of the upstream server. Note that the host value is case sensitive.
	Host string `json:"host"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// The Service name.
	Name *string `json:"name,omitempty"`
	// The path to be used in requests to the upstream server.
	Path *string `json:"path,omitempty"`
	// The upstream server port.
	Port *int64 `json:"port,omitempty"`
	// The protocol used to communicate with the upstream.
	Protocol *Protocol `json:"protocol,omitempty"`
	// The timeout in milliseconds between two successive read operations for transmitting a request to the upstream server.
	ReadTimeout *int64 `json:"read_timeout,omitempty"`
	// The number of retries to execute upon failure to proxy.
	Retries *int64 `json:"retries,omitempty"`
	// An optional set of strings associated with the Service for grouping and filtering.
	Tags []string `json:"tags,omitempty"`
	// Additional Subject Alternative Names that can be matched on Upstream server's TLS certificate (in addition to `host`).
	TLSSans *TLSSans `json:"tls_sans,omitempty"`
	// Whether to enable verification of upstream server TLS certificate. If set to `null`, then the Nginx default is respected.
	TLSVerify *bool `json:"tls_verify,omitempty"`
	// Maximum depth of chain while verifying Upstream server's TLS certificate. If set to `null`, then the Nginx default is respected.
	TLSVerifyDepth *int64 `json:"tls_verify_depth,omitempty"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	// The timeout in milliseconds between two successive write operations for transmitting a request to the upstream server.
	WriteTimeout *int64 `json:"write_timeout,omitempty"`
}

func (s *ServiceOutput) GetCaCertificates() []string {
	if s == nil {
		return nil
	}
	return s.CaCertificates
}

func (s *ServiceOutput) GetClientCertificate() *ClientCertificate {
	if s == nil {
		return nil
	}
	return s.ClientCertificate
}

func (s *ServiceOutput) GetConnectTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.ConnectTimeout
}

func (s *ServiceOutput) GetCreatedAt() *int64 {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ServiceOutput) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *ServiceOutput) GetHost() string {
	if s == nil {
		return ""
	}
	return s.Host
}

func (s *ServiceOutput) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ServiceOutput) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ServiceOutput) GetPath() *string {
	if s == nil {
		return nil
	}
	return s.Path
}

func (s *ServiceOutput) GetPort() *int64 {
	if s == nil {
		return nil
	}
	return s.Port
}

func (s *ServiceOutput) GetProtocol() *Protocol {
	if s == nil {
		return nil
	}
	return s.Protocol
}

func (s *ServiceOutput) GetReadTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.ReadTimeout
}

func (s *ServiceOutput) GetRetries() *int64 {
	if s == nil {
		return nil
	}
	return s.Retries
}

func (s *ServiceOutput) GetTags() []string {
	if s == nil {
		return nil
	}
	return s.Tags
}

func (s *ServiceOutput) GetTLSSans() *TLSSans {
	if s == nil {
		return nil
	}
	return s.TLSSans
}

func (s *ServiceOutput) GetTLSVerify() *bool {
	if s == nil {
		return nil
	}
	return s.TLSVerify
}

func (s *ServiceOutput) GetTLSVerifyDepth() *int64 {
	if s == nil {
		return nil
	}
	return s.TLSVerifyDepth
}

func (s *ServiceOutput) GetUpdatedAt() *int64 {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ServiceOutput) GetWriteTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.WriteTimeout
}

// Service entities, as the name implies, are abstractions of each of your own upstream services. Examples of Services would be a data transformation microservice, a billing API, etc. The main attribute of a Service is its URL (where Kong should proxy traffic to), which can be set as a single string or by specifying its `protocol`, `host`, `port` and `path` individually. Services are associated to Routes (a Service can have many Routes associated with it). Routes are entry-points in Kong and define rules to match client requests. Once a Route is matched, Kong proxies the request to its associated Service. See the [Proxy Reference][proxy-reference] for a detailed explanation of how Kong proxies traffic.
type Service struct {
	// Array of `CA Certificate` object UUIDs that are used to build the trust store while verifying upstream server's TLS certificate. If set to `null` when Nginx default is respected. If default CA list in Nginx are not specified and TLS verification is enabled, then handshake with upstream server will always fail (because no CA are trusted).
	CaCertificates []string `json:"ca_certificates,omitempty"`
	// Certificate to be used as client certificate while TLS handshaking to the upstream server.
	ClientCertificate *ClientCertificate `json:"client_certificate,omitempty"`
	// The timeout in milliseconds for establishing a connection to the upstream server.
	ConnectTimeout *int64 `json:"connect_timeout,omitempty"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the Service is active. If set to `false`, the proxy behavior will be as if any routes attached to it do not exist (404). Default: `true`.
	Enabled *bool `json:"enabled,omitempty"`
	// The host of the upstream server. Note that the host value is case sensitive.
	Host string `json:"host"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// The Service name.
	Name *string `json:"name,omitempty"`
	// The path to be used in requests to the upstream server.
	Path *string `json:"path,omitempty"`
	// The upstream server port.
	Port *int64 `json:"port,omitempty"`
	// The protocol used to communicate with the upstream.
	Protocol *Protocol `json:"protocol,omitempty"`
	// The timeout in milliseconds between two successive read operations for transmitting a request to the upstream server.
	ReadTimeout *int64 `json:"read_timeout,omitempty"`
	// The number of retries to execute upon failure to proxy.
	Retries *int64 `json:"retries,omitempty"`
	// An optional set of strings associated with the Service for grouping and filtering.
	Tags []string `json:"tags,omitempty"`
	// Additional Subject Alternative Names that can be matched on Upstream server's TLS certificate (in addition to `host`).
	TLSSans *TLSSans `json:"tls_sans,omitempty"`
	// Whether to enable verification of upstream server TLS certificate. If set to `null`, then the Nginx default is respected.
	TLSVerify *bool `json:"tls_verify,omitempty"`
	// Maximum depth of chain while verifying Upstream server's TLS certificate. If set to `null`, then the Nginx default is respected.
	TLSVerifyDepth *int64 `json:"tls_verify_depth,omitempty"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	// Helper field to set `protocol`, `host`, `port` and `path` using a URL. This field is write-only and is not returned in responses.
	URL *string `json:"url,omitempty"`
	// The timeout in milliseconds between two successive write operations for transmitting a request to the upstream server.
	WriteTimeout *int64 `json:"write_timeout,omitempty"`
}

func (s *Service) GetCaCertificates() []string {
	if s == nil {
		return nil
	}
	return s.CaCertificates
}

func (s *Service) GetClientCertificate() *ClientCertificate {
	if s == nil {
		return nil
	}
	return s.ClientCertificate
}

func (s *Service) GetConnectTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.ConnectTimeout
}

func (s *Service) GetCreatedAt() *int64 {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *Service) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *Service) GetHost() string {
	if s == nil {
		return ""
	}
	return s.Host
}

func (s *Service) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Service) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Service) GetPath() *string {
	if s == nil {
		return nil
	}
	return s.Path
}

func (s *Service) GetPort() *int64 {
	if s == nil {
		return nil
	}
	return s.Port
}

func (s *Service) GetProtocol() *Protocol {
	if s == nil {
		return nil
	}
	return s.Protocol
}

func (s *Service) GetReadTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.ReadTimeout
}

func (s *Service) GetRetries() *int64 {
	if s == nil {
		return nil
	}
	return s.Retries
}

func (s *Service) GetTags() []string {
	if s == nil {
		return nil
	}
	return s.Tags
}

func (s *Service) GetTLSSans() *TLSSans {
	if s == nil {
		return nil
	}
	return s.TLSSans
}

func (s *Service) GetTLSVerify() *bool {
	if s == nil {
		return nil
	}
	return s.TLSVerify
}

func (s *Service) GetTLSVerifyDepth() *int64 {
	if s == nil {
		return nil
	}
	return s.TLSVerifyDepth
}

func (s *Service) GetUpdatedAt() *int64 {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *Service) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *Service) GetWriteTimeout() *int64 {
	if s == nil {
		return nil
	}
	return s.WriteTimeout
}
