workflowVersion: 1.0.0
speakeasyVersion: 1.541.2
sources:
  gateway:
    inputs:
      - location: ./openapi.yaml
    overlays:
      - location: ./overlay.yaml
    registry:
      location: registry.speakeasyapi.dev/kong/kong/gateway
targets:
  tf:
    target: terraform
    source: gateway
    output: .
