// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-kong-gateway/internal/sdk/models/shared"
)

func (r *KeyAuthResourceModel) RefreshFromSharedKeyAuth(ctx context.Context, resp *shared.KeyAuth) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
		r.ID = types.StringPointerValue(resp.ID)
		r.Key = types.StringPointerValue(resp.Key)
		if resp.Tags != nil {
			r.Tags = make([]types.String, 0, len(resp.Tags))
			for _, v := range resp.Tags {
				r.Tags = append(r.Tags, types.StringValue(v))
			}
		}
		r.TTL = types.Int64PointerValue(resp.TTL)
	}

	return diags
}

func (r *KeyAuthResourceModel) ToOperationsCreateKeyAuthWithConsumerRequest(ctx context.Context) (*operations.CreateKeyAuthWithConsumerRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var consumerID string
	consumerID = r.ConsumerID.ValueString()

	var workspace string
	workspace = r.Workspace.ValueString()

	keyAuthWithoutParents, keyAuthWithoutParentsDiags := r.ToSharedKeyAuthWithoutParents(ctx)
	diags.Append(keyAuthWithoutParentsDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateKeyAuthWithConsumerRequest{
		ConsumerID:            consumerID,
		Workspace:             workspace,
		KeyAuthWithoutParents: keyAuthWithoutParents,
	}

	return &out, diags
}

func (r *KeyAuthResourceModel) ToOperationsDeleteKeyAuthWithConsumerRequest(ctx context.Context) (*operations.DeleteKeyAuthWithConsumerRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var consumerID string
	consumerID = r.ConsumerID.ValueString()

	var keyAuthID string
	keyAuthID = r.ID.ValueString()

	var workspace string
	workspace = r.Workspace.ValueString()

	out := operations.DeleteKeyAuthWithConsumerRequest{
		ConsumerID: consumerID,
		KeyAuthID:  keyAuthID,
		Workspace:  workspace,
	}

	return &out, diags
}

func (r *KeyAuthResourceModel) ToOperationsGetKeyAuthWithConsumerRequest(ctx context.Context) (*operations.GetKeyAuthWithConsumerRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var consumerID string
	consumerID = r.ConsumerID.ValueString()

	var keyAuthID string
	keyAuthID = r.ID.ValueString()

	var workspace string
	workspace = r.Workspace.ValueString()

	out := operations.GetKeyAuthWithConsumerRequest{
		ConsumerID: consumerID,
		KeyAuthID:  keyAuthID,
		Workspace:  workspace,
	}

	return &out, diags
}

func (r *KeyAuthResourceModel) ToSharedKeyAuthWithoutParents(ctx context.Context) (*shared.KeyAuthWithoutParents, diag.Diagnostics) {
	var diags diag.Diagnostics

	createdAt := new(int64)
	if !r.CreatedAt.IsUnknown() && !r.CreatedAt.IsNull() {
		*createdAt = r.CreatedAt.ValueInt64()
	} else {
		createdAt = nil
	}
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	key := new(string)
	if !r.Key.IsUnknown() && !r.Key.IsNull() {
		*key = r.Key.ValueString()
	} else {
		key = nil
	}
	var tags []string
	if r.Tags != nil {
		tags = make([]string, 0, len(r.Tags))
		for _, tagsItem := range r.Tags {
			tags = append(tags, tagsItem.ValueString())
		}
	}
	ttl := new(int64)
	if !r.TTL.IsUnknown() && !r.TTL.IsNull() {
		*ttl = r.TTL.ValueInt64()
	} else {
		ttl = nil
	}
	out := shared.KeyAuthWithoutParents{
		CreatedAt: createdAt,
		ID:        id,
		Key:       key,
		Tags:      tags,
		TTL:       ttl,
	}

	return &out, diags
}
