name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - ".github/workflows/test.yaml"
      - "**.go"

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests (Terraform ${{ matrix.terraform-version }}, Kong ${{ matrix.kong-gateway-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Only test against one version for now as these tests are not
        # namespaced and will conflict
        terraform-version:
          - "1.11.*"
        kong-gateway-version:
          - "3.12"
          #- "3.11"
          #- "3.10"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@cd53bc84d5e2fd85362f4cb840513e06427082d3 # v4
        with:
          go-version-file: "go.mod"
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - uses: Kong/kong-license@bfa1c17600a68d879042f44a9ec3fb5b60f4fad5 # master @ 20250819
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Kong Gateway
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: |
          curl -Ls https://get.konghq.com/quickstart | bash -s -- -t ${{ matrix.kong-gateway-version }} -e KONG_LICENSE_DATA
      - run: make acceptance
      - name: Tear Down Kong Gateway
        run: |
          curl -Ls https://get.konghq.com/quickstart | bash -s -- -d
